<?php

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly
}

/**
 * Adds Germanized Invoice settings.
 *
 * @class 		WC_GZDP_Settings_Tab_Invoices
 * @version		3.0.0
 * @author 		Vendidero
 */
class WC_GZDP_Settings_Tab_Invoices extends WC_GZD_Settings_Tab_Invoices {

	public function get_tab_settings( $current_section = '' ) {
		$helper   = WC_GZDP_Invoice_Helper::instance();
		$settings = $helper->get_settings();

		return $settings;
	}

	public function supports_disabling() {
		return true;
	}

	protected function get_enable_option_name() {
		return 'woocommerce_gzdp_invoice_enable';
	}

	public function is_enabled() {
		return 'yes' === get_option( $this->get_enable_option_name() );
	}

	protected function before_save( $settings, $current_section = '' ) {
		$helper = WC_GZDP_Invoice_Helper::instance();
		$helper->check_number_reset( $settings );

		parent::before_save( $settings, $current_section ); // TODO: Change the autogenerated stub
	}

	protected function after_save( $settings, $current_section = '' ) {
		$helper = WC_GZDP_Invoice_Helper::instance();
		$helper->check_pdf_template_version( $settings );

		parent::after_save( $settings, $current_section );
	}
}